spring.application.name=supermarket
# Cau hình ket noi database
spring.datasource.url=jdbc:sqlserver://localhost\\MSSQLSERVER:1433;databaseName=HSF-Project;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Không su dung Spring Data JPA
spring.data.jpa.repositories.enabled=true
# Cau hinh server port
server.port=8080
#Cau hinh resource bundle
spring.messages.basename=Messages
spring.messages.encoding=UTF-8


#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
# Config context path


#spring boot mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contact.edutest.vn@gmail.com
spring.mail.password=gapkmfnwqhmdgcbh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
